# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LockReact' do
  pod 'Lock', '~> 1.24'
  pod 'Lock/TouchID'
  pod 'Lock/SMS'
  pod 'Lock/Email'
end
